const strings = {
  searchPattern: "Desenlerde ara",
  pressFocus: "Odaklanmak için '/' tuşuna basın",
  title: "SVG Desen Oluşturucu",
  heading: "Projeleriniz için özelleştirilebilir <span>SVG kalıpları</span>",
  keywords: "svg desenleri, desenler, svg arka planlar, vektör duvar kağıdı, desen oluşturucu",
  patterns: "desenler",
  license: "MIT Lisansı",
  free: "Ücretsiz",
  description: "Tekrarlanabilir SVG desenleri oluşturmak için basit bir çevrimiçi desen üreteci.",
  description2: "Görüntü kalitesinde ödün vermeden web sitenizi hızlandırın.",
  description3: "Web sitesi arka planlar, giyim, markalaşma, paketleme tasarımı ve daha fazlası için mükemmel.",
  filter: "Filtre",
  sort: "Sırala",
  filterMode: "Moda göre Filtrele",
  filterColors: "Renge göre Filtrele",
  allModes: "Tüm modlar",
  stroke: "Kenar",
  fill: "Dolgu",
  allColors: "Tüm renkler",
  colors: "renkler",
  latest: "En Son",
  oldest: "En Eski",
  alphabetical: "Alfabetik",
  updateDate: "Güncelleme Tarihi",
  changeTheme: "Temayı Değiştir",
  changelog: "Değişiklik Notları",
  features: "Özellikler",
  downloads: "Downloads",
  translate: "Çevir",
  privacy: "Gizlilik Politikası",
  privacyFull: "Bu uygulama herhangi bir kullanıcı verisini toplamaz veya saklamaz",
  signUp: "Proje güncellemeleri için kaydolun ve gelen kutunuza aylık teslim edilen ücretsiz desenler alın",
  email: "E-posta adresiniz",
  sendPatterns: "Bana desenler gönder",
  zoom: "Zum",
  hSpacing: "Yatay boşluk",
  vSpacing: "Dikey Boşluk",
  hPosition: "Horizontal Position",
  vPosition: "Vertical Position",
  angle: "Açı",
  inspire: "İlham",
  random: "Rastgele Desen Çiz",
  reset: "Sıfırla",
  copy: "Kopyala",
  copyCSS: "CSS Kopyala",
  copySVG: "SVG Kopyala",
  download: "İndir",
  downloadSVG: "SVG dosyası olarak indir",
  downloadPNG: "PNG dosyası olarak indir",
  dimensions: "Ebatlar",
  width: "Genişlik",
  height: "Yükseklik",
  hide: "Arayüzü Gizle",
  lock: "Kilitle",
  unlock: "Kilidi Aç",
  checkOut: "SVG desenleri ve arka planlar oluşturmayı seviyorsanız, bunu kontrol etmelisiniz.",
  generate: "Ücretsiz olarak tamamen özelleştirilebilir SVG desenleri oluşturun.",
  patternsCount: "140+ desen https://pattern.monster adresinde",
  square: "Kare",
  rounded: "Yuvarlak",
  join: "Bağlantı Modu",
  tweet: "Tweet'inizi paylaşın",
  waves: "Dalgalar",
  chevron: "Zikzak Çıta",
  straightLines: "Doğru çizgiler",
  crossSection: "Enine Kesit",
  brickWall: "Tuğla Duvarlar",
  herringbone: "Herringbone",
  flower: "Çiçek",
  plus: "Artı",
  circles: "Daireler",
  concentricCircles: "Eş Merkezli Daireler",
  adjointedCircles: "Eklenen Daireler",
  adjointedDiamonds: "Eklenmiş Karolar",
  diamonds: "Karolar",
  hexagon: "Altıgen",
  overlappingHexagons: "Örtüşen Altıgenler",
  squaresSquares: "Kareler ve Kareler",
  squaresDiamonds: "Kareler ve Karolar",
  squaresCircles: "Kareler ve Daireler",
  squaresPlus: "Kareler ve Artı",
  squaresStars: "Kareler ve Yıldızlar",
  starsLines: "Yıldızlar &amp; Çizgiler",
  triangles: "Üçgenler",
  invertedTriangles: "Ters Üçgenler",
  checkerboard: "Dama Tahtası",
  japanesePattern: "Japon Deseni",
  eyes: "Gözler",
  jigsaw: "Testere",
  railroad: "Demir Yolu",
  octagons: "Sekizgen",
  lines: "Çizgiler",
  scales: "Skalalar",
  leaves: "Yapraklar",
  pipes: "Borular",
  zebra: "Zebra",
  memphis: "Memphis",
  greekKey: "Yunan Anahtarı",
  chinese: "Çin Deseni",
  newPattern: "Yeni Desen",
  doubleBubble: "Çift Kabarcık",
  stars: "Yıldızlar",
  semicircles: "Yarım daire",
  songket: "Songket Deseni",
};

export default { strings };
